### ISSUE TITLE
Deleting a person linked to an organization deletes the org as well

### ISSUE THREAD

**Issue by tristanlatr** [LesFruitsDefendus/saskatoon-ng#125] opened 2022-03-24 16:47 UTC
The workaround is to associate the org with a another contact person before deleting the person.

But still, I feel like it should not delete the organization expect explicitly asked. 

<img width="548" alt="by default 2022-03-24 at 12 45 51 PM" src="https://user-images.githubusercontent.com/19967168/159967576-4950ef66-c61a-4ad0-9de3-b682e185d021.png">

**Comment by yokwejuste** [comment] 2022-03-28 21:22
What do you want now? The issue is not clear give more highlights on it. Do you wish to delete just the user and not the organisation that was exiting relatively to the user or what ?

**Comment by yokwejuste** [comment] 2022-03-28 21:24
> The workaround is to associate the org with a another contact person before deleting the person.
> 
> But still, I feel like it should not delete the organization expect explicitly asked.
> 
> <img alt="by default 2022-03-24 at 12 45 51 PM" width="548" src="https://user-images.githubusercontent.com/19967168/159967576-4950ef66-c61a-4ad0-9de3-b682e185d021.png">

## Please @tristanlatr be clear in this issue
Waht do you want now? The issue is not clear give more highlights on it. Do you wish to delete just the user and not the organisation that was exiting relatively to the user or what ?

**Comment by tristanlatr** [comment] 2022-03-29 05:37
Hello @yokwejuste 

> Do you wish to delete just the user and not the organisation that was exiting relatively to the user or what?

Yes exactly. Deleting the person should not delete the organization. It should simply unlink the contact person fro the organization. And if that poses and issue for the database model, I think the form should simply refuse to delete a person that is still linked to an organization. 

Talk to you later,

**Comment by yokwejuste** [comment] 2022-03-29 12:16
Can I be assigned to this task @tristanlatr ? 

And if yes, please make it clear by assigning the issue to my name! 

Thanks!

**Comment by tristanlatr** [comment] 2022-03-30 02:30
Hello @yokwejuste,

I think you can work on this issue. Contributors should read the comments of the issue before start working on something.

But if you prefer, I can assign you this issue in github for the time being. But keep in mind that it's not a standard practice that we've put in place and other issues mind be worked on by other contributors even if they are not assigned to anyone in the github UI. 

Hope this answers your question,

**Comment by yokwejuste** [comment] 2022-03-30 21:17
Yes sir, copied! Working on the implement and preparing the PR.

**Comment by diananova** [comment] 2022-04-07 23:21
Any updates? I could try looking into it, seems like a pretty serious bug.

**Comment by tristanlatr** [comment] 2022-04-08 16:02
Hello @diananova,

Yes it would be good to have this fixed. 

I feel like the form should simply refuse to delete a person that is still linked to an organization and say that a another contact person should be assigned first. It's probably the simplest way to solve that issue.

Since we have no news regarding this issue for more than a week now, I think it's OK if you start working on it as well. 

Thanks,

Talk to you later,

**Comment by diananova** [comment] 2022-04-08 20:03
Great, on it!

**Closed** 2022-05-31 00:49 UTC
Labels: high priority
